# Generated by Django 5.0.7 on 2024-08-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='category_of_drinks',
            options={'verbose_name': 'Категорию напитков', 'verbose_name_plural': 'Категории напитков'},
        ),
        migrations.AlterModelOptions(
            name='category_of_pizza',
            options={'verbose_name': 'Категорию пиццы', 'verbose_name_plural': 'Категории пиццы'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Пиццу', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='basket',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category_of_drinks',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='category_of_pizza',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='drink',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Укажите скидку на напиток', max_digits=5, null=True, verbose_name='Скидка на напиток'),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите сюда ссылку на изображение с напитком', null=True, upload_to='pizza/%Y/%m/%d/', verbose_name='Изображение напитка'),
        ),
        migrations.AddField(
            model_name='drink',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Укажите скидку на пиццу', max_digits=5, null=True, verbose_name='Скидка на пиццу'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите сюда ссылку на изображение с пиццей', null=True, upload_to='pizza/%Y/%m/%d/', verbose_name='Изображение пиццы'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, help_text='Укажите URL-слаг', max_length=200, null=True, unique=True, verbose_name='URL'),
        ),
    ]
