# Generated by Django 5.0.7 on 2024-08-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_basket_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'ordering': ['user'], 'verbose_name': 'Корзину', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='drink',
            options={'ordering': ['name'], 'verbose_name': 'Напиток', 'verbose_name_plural': 'Напитки'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'ordering': ['name'], 'verbose_name': 'Пиццу', 'verbose_name_plural': 'Пиццы'},
        ),
        migrations.AlterModelTable(
            name='basket',
            table='Корзины пользователей',
        ),
        migrations.AlterModelTable(
            name='category_of_drinks',
            table='Категории напитков',
        ),
        migrations.AlterModelTable(
            name='category_of_pizza',
            table='Категории пиццы',
        ),
        migrations.AlterModelTable(
            name='drink',
            table='Напитки',
        ),
        migrations.AlterModelTable(
            name='order',
            table='Заказы',
        ),
        migrations.AlterModelTable(
            name='pizza',
            table='Пиццы',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Пользователи',
        ),
    ]
