# Generated by Django 5.0.7 on 2024-08-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_basket_options_alter_drink_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='prise',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='prise',
            new_name='price',
        ),
    ]
